### ISSUE TITLE
[API Spec issue] '단일 파일 하이라이트 추가하기', '단일 파일 단일 하이라이트 삭제하기' 관련 논의 필요

### ISSUE THREAD

**Issue by niceoasi** [mash-up-kr/munggoo-backend#38]
#### 대신 '단일 파일 하이라이트 업데이트' 정도로 수정 되면 좋을 것 같아요

ref: [단일 파일 하이라이트 추가하기](https://github.com/mash-up-kr/munggoo-backend/wiki/Munggoo-API-document#단일-파일-하이라이트-추가하기)
ref: [단일 파일 단일 하이라이트 삭제하기' 관련 논의 필요](https://github.com/mash-up-kr/munggoo-backend/wiki/Munggoo-API-document#단일-파일-단일-하이라이트-삭제하기)

**Comment by jo-bata** [comment]
말씀하신 부분 반영해서 배포해놨습니다! 확인해주세요!
