### ISSUE TITLE
[API Spec issue] 모든 파일 목록 조회하기 API 스펙 대로 변경 되지 않음.

### ISSUE THREAD

**Issue by niceoasi** [mash-up-kr/munggoo-backend#39]
ref: [모든 파일 목록 조회하기](https://github.com/mash-up-kr/munggoo-backend/wiki/Munggoo-API-document#모든-파일-목록-조회하기)

```
Get => http://15.164.62.183:8080/v1/devices/6/files

response:
[
    {
        "id": 1,
        "name": "A%20Simple%20PDF%20File12-1.pdf"
    }
]
```

**Comment by jo-bata** [comment]
배포가 다시 이루어지지 않은 것 같습니다.
하이라이트 업데이트 API 완성하고 다시 한번 배포하겠습니다!

**Comment by jo-bata** [comment]
재배포하였습니다! 이제 잘 될겁니다. 확인해주세요!

![image](https://user-images.githubusercontent.com/36880294/62703888-280ce200-ba25-11e9-913f-8ccf571a344f.png)
