### ISSUE TITLE
[API Spec issue] 단일 파일 하이라이트 추가하기 API의 isImportant 타입이 상이함

### ISSUE THREAD

**Issue by niceoasi** [mash-up-kr/munggoo-backend#46]
ref: [단일 파일 하일라이트 추가](https://github.com/mash-up-kr/munggoo-backend/wiki/Munggoo-API-document#단일-파일-하이라이트-추가하기)

위 단일 파일 하일라이트 추가 하기 API의 [Request]와 [Response]의 isImportant 타입이 서로 다르네요.

이 부분은 통일 시키는게 더 나아 보이는데, 확인 부탁 드려요.

**Comment by jo-bata** [comment]
@niceoasi 
Enum으로 정의해서 컨버팅한 것을 내려주고 있습니다.
Enum 타입을 활용해 보고 싶어서 쓴 것이라 그대로 가면 안될까요??

**Comment by jo-bata** [comment]
@niceoasi 
그게 더 나아보이네요 수정하겠습니다!
